<html>

<head>
    <?php $pageTitle = 'Privacy Policy' ?>
    <?php include './../include/head-link.php' ?>
    <?php include './../include/constant.php' ?>
</head>

<body class="pt-0">
    <!-- Header Component -->
    <?php include './../include/header.php' ?>
    <main class="mainContent">
        <section class="innerBanner innerBanner-sm">
            <div class="container">
                <div class="text-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb position-relative">
                            <li class="breadcrumb-item"><a href="<?php echo BASE_URL?>/">Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Legal</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Privacy Policy</li>
                        </ol>
                    </nav>
                    <h1 class="mb-0">Privacy Policy</h1>
                </div>
            </div>
        </section>

        <section class="cmsPages py-80 pb-0">
            <div class="container container-sm">
                <p>We use your personal data to provide and improve the service. By using the service, you agree to the collection and use of information in accordance with this privacy policy.</p>

                <h3>Interpretation and Definitions</h3>

                <h4>Interpretation</h4>

                <p>The words for which the initial letter is capitalised have meanings defined under the following conditions: The following definitions shall have the same meaning regardless of whether they appear in singular or plural.</p>

                <h4>Definitions</h4>

                <p>For the purposes of this privacy policy:</p>

                <ul>
                <li> A service account is a unique account created for you to access our service or parts of our service.</li>

                <li>  Affiliate interest means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for the election of directors or other managing authority.</li>

                <li>  Company Ltd. (referred to as either "the company," "we," "us," or "our'' in this agreement) refers to Hyper Automation Pvt. Ltd., 502, Vikram Heights, Yeshwant Niwas Road., Race Course Road, Indore, Madhya Pradesh 452001.</li>

                <li> Cookies are small files that are placed on your computer, mobile device, or any other device by a website, containing the details of your browsing history on that website, among its many uses.</li>

                <li> Country refers to: India</li>

                <li>  Device service means any device that can access the service, such as a computer, a cell phone, or a digital tablet.</li>

                <li>  Personal data is any information that relates to an identified or identifiable individual.</li>

                <li>  Service refers to the website.</li>

                <li> A service company provider is any natural or legal person who processes the data on behalf of the company. It refers to third-party companies or individuals employed by the company to facilitate the service, to provide the service on behalf of the company, to perform services related to the service, or to assist the company in analysing how the service is used.</li>

                <li> A third-party social media service user refers to any website or any social network website through which a user can log in or create an account to use the service.</li>

                <li> Usage data refers to data collected automatically, either generated by the use of the service or from the service infrastructure itself (for example, the duration of a page visit).</li>

                <li>  The website refers to AIRA, accessible at https://aira.fr.</li>

                <li> You Company means the individual accessing or using the service, or the company, or other legal entity on behalf of which such individual is accessing or using the service, as applicable.</li>

                </ul>

                <h3>Collecting and Using Your Personal Data</h3>
                <h4>Personal Data </h4>

              <p>While using our service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>

              <ul>
                <li>Email address </li>
                <li>First name and last name </li>
                <li>Phone number </li>
                <li>Address, State, Province, ZIP/Postal Code, City </li>
                <li>Usage Data </li>
              </ul>

              <h3>Usage Data</h3>

             <p> Usage data is collected automatically when using the service. </p>

             <p> Usage data may include information such as your device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.</p>

             <p>  When you access the service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your unique mobile device ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers, and other diagnostic data.</p>

             <p>We may also collect information that your browser sends whenever you visit our service or when you access the service by or through a mobile device.</p>

            <h3>Information from third-party social media services</h3>

            <p>The company allows you to create an account and log in to use the service through the following third-party social media services:</p>

            <ul>
              <li>Google</li>
              <li>Facebook</li>
              <li>Instagram</li>
              <li>Twitter</li>
              <li>LinkedIn</li>
            </ul>
          <p>  If you decide to register through or otherwise grant us access to a third-party social media service, we may collect personal data that is already associated with your third-party social media service's account, such as your name, your email address, your activities, or your contact list associated with that account.</p>

          <p> You may also have the option of sharing additional information with the company through your third-party social media service's account. If you choose to provide such information and personal data during registration or otherwise, you are giving the company permission to use, share, and store it in a manner consistent with this privacy policy</p>

          <h3>Tracking technologies and cookies</h3>

          <p>We use cookies and similar tracking technologies to track activity on our service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyse our service. The technologies we use may include:</p>

          <ul>
          <li><strong>Browser cookies or browser cookies:</strong> A cookie is a small file placed on your device. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some parts of our service. Unless you have adjusted your browser setting so that it will refuse cookies, our service may use cookies.

          <li><strong>  Web Beacons: </strong>Certain sections of our service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
          </ul>

          <p>Cookies can be "persistent" or "session" cookies. Persistent cookies remain on your personal computer or mobile device when you go offline, while session cookies are deleted as soon as you close your web browser. </p>

          <p>We use both session and persistent cookies for the purposes set out below:</p>

          <p>Necessary and Essential Cookies</p>

          <p>Type: Session Cookies </p>

          <p>Administered by: Us

          <p>Purpose: These cookies are essential to provide you with services available through the website and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these cookies, the services that you have asked for cannot be provided, and we only use these cookies to provide you with those services.</p>

          <p>Cookies Policy and Notice Acceptance Cookies</p>

          <p>Type: Persistent cookies</p>

          <p>Administered by: US </p>

          <p>Purpose: These cookies allow us to remember choices you make when you use the website, such as your login details or language preference. The purpose of these cookies is to provide you with a more personal experience and to avoid having to re-enter your preferences every time you use the website. </p>

          <p>For more information about the cookies we use and your choices regarding cookies, please visit our <a href="mailto:connect@aira.fr">connect@aira.fr</a></p>

          <h3>Use of Your Personal Data</h3>

          <h4>The company may use personal data for the following purposes :</h4>

        <p>  The company may use personal data for the following purposes : </p>

        <p>  To provide and maintain our service, including to monitor the usage of our service.</p>

        <p>   To manage your account: Service to manage your registration as a user of the service. The personal data you provide can give you access to different functionalities of the service that are available to you as a registered user. </p>

        <p>  For the performance of a contract, use the development, compliance, and undertaking of the purchase contract for the products, items, or services you have purchased or of any other contract with us through the service. </p>

        <p>   To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>

        <p>   To provide you with news, special offers, and general information about other goods, services, and events that we offer that are similar to those that you have already purchased or inquired about, unless you have opted not to receive such information. </p>

        <p>   To manage your requests, attend and manage your requests with us.</p>

        <p>   For business transfers, we may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganisation, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which personal data held by us about our service users is among the assets transferred. </p>

        <p>   For other purposes: We may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our service, products, services, marketing, and your experience. </p>

        <h4>We may share your personal information in the following situations :</h4>

        <ul>
        <li> <strong>  With Service Providers :</strong> We may share your personal information with service providers to monitor and analyse the use of our service and to contact you. </li>

        <li> <strong> For business transfers :</strong> We we may share or transfer your personal information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company. </li>

        <li> <strong> With Affiliates:</strong> We We may share your information with our affiliates, in which case we will require those affiliates to honour this privacy policy. Affiliates include our parent company and any other subsidiaries, joint venture partners, or other companies that we control or that are under common control with us. </li>

        <li> <strong>  With business partners :</strong> We may share your information with our business partners to offer you certain products, services, or promotions. </li>

        <li> <strong> With other users:</strong> When you share personal information or otherwise interact in public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If you interact with other users or register through a third-party social media service, your contacts on the third-party social media service may see your name, profile, pictures, and description of your activity. Similarly, other users will be able to view descriptions of your activity, communicate with you, and view your profile. </li>

       <li> <strong> With Your Consent</strong> : We may disclose Your personal information for any other purpose with Your Consent. </li>
        </ul>

        <h3>Transfer of Your Personal Data</h3>

        <p>Your information, including personal data, is processed at the company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to and maintained on computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those in your jurisdiction.</p>

       <p> Your consent to this privacy policy, followed by your submission of such information, represents your agreement to that transfer. </p>

       <p>  The company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this privacy policy, and no transfer of your personal data will take place to an organisation or a country unless there are adequate controls in place, including the security of your data and other personal information.</p>

       <h3>Delete Your Personal Data</h3>

       <p>You have the right to delete or request that we assist in deleting the personal data that we have collected about you.</p>

       <p> Our service may give you the ability to delete certain information about you from within the service. </p>

        <p> You may update, amend, or delete your information at any time by signing in to your account, if you have one, and visiting the account settings section that allows you to manage your personal information. You may also contact us to request access to, correct, or delete any personal information that you have provided to us.</p>

        <p> Please note, however, that we may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

        <h3>Disclosure of Your Personal Data</h3>

        <h4>  Business Transactions</h4>
        <p> If the company is involved in a merger, acquisition, or asset sale, your personal data may be transferred. We will provide notice before your personal data is transferred and becomes subject to a different privacy policy.</p>

        <h4>  Law enforcement</h4>
        <p> Under certain circumstances, the company may be required to disclose your personal data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).</p>

        <h4>  Other legal requirements </h4>
         <p> The company may disclose your personal data in the good-faith belief that such action is necessary to: </p>

         <ul>
       <li> Comply with a legal obligation</li>
       <li>  Protect and defend the rights or property of the company.</li>
       <li>  Prevent or investigate possible wrongdoing in connection with the service.</li>
       <li>  Protect the personal safety of users of the service or the public.</li>
       <li>  Protect against legal liability. </li>
        </ul>

        <h3>Security of Your Personal Data</h3>
        <p>The security of your personal data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its absolute security.</p>

       <h3> Children's Privacy</h3>
        <p>Our service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with personal data, please contact us. If we become aware that we have collected personal data from anyone under the age of 13 without verification of parental consent, we will take steps to remove that information from our servers.</p>

        <p>If we need to rely on consent as a legal basis for processing your information and your country requires consent from a parent, we may require your parent's consent before we collect and use that information.</p>

        <h3>Links to other websites</h3>
       <p> Our service may contain links to other websites that are not operated by us. If you click on a third-party link, you will be directed to that third-party's site. We strongly advise you to review the privacy policy of every site you visit.</p>

      <p> We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>

        <h3> Changes to this Privacy Policy </h3>
       <p> We may update our privacy policy from time to time. We will notify you of any changes by posting the new privacy policy on this page. <br /> We will let you know via email and/or a prominent notice on our service prior to the change becoming effective and update the "Last updated" date at the top of this privacy policy. <br /> You are advised to review this privacy policy periodically for any changes. Changes to this privacy policy are effective when they are posted on this page. </p>

      <h3>Contact Us</h3>
      <p> If you have any questions about this privacy policy, you can contact us at <a href="mailto:connect@aira.fr">connect@aira.fr</a> </p>
            </div>
        </section>
    </main>
    <?php include './../include/footer.php' ?>
    <?php include './../include/script.php' ?>
</body>

</html>